#!/bin/sh

echo `date` $0 `date -u` begin

export envir=${envir:-prod}
export REGIONAL_RR=${REGIONAL_RR:-1}

###############################
# Specify NET and RUN name
##############################
export NET=${NET:-nam}
export RUN=${RUN:-nam}

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export outid=${outid:-"LL$job"}
export jobid=${jobid:-"${outid}.o${pid}"}

export RADMON_SUFFIX=${RADMON_SUFFIX:-$NET}
export DATAROOT=${DATAROOT:-/tmpnwprod2}
export DATA=${DATA:-${DATAROOT}/${jobid}}
echo "DATAROOT = $DATAROOT"
echo "DATA = $DATA"

mkdir -p $DATA
cd $DATA

export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}
echo "jlogfile = $jlogfile"

####################################
# Determine Job Output Name on System
####################################
export pgmerr=errfile
export rgnHH=${rgnHH:-${cyc}z}
export rgnTM=${rgnTM:-tm06}
echo rgnHH = $rgnHH

##############################################
# Specify Execution Areas
##############################################
#export HOMEnam=${HOMEnam:-${NWROOT}/nam_radmon.v2.0.0}  # need to use version here
export SCRnam=${SCRnam:-${HOMEnam}/scripts}
#export PARMnam=${PARMnam:-${HOMEnam}/parm}

echo HOMEnam = $HOMEnam
echo SRCnam = $SRCnam

#############################################
# COMOUT - WHERE GSI OUTPUT RESIDES
# TANKverf - WHERE OUTPUT DATA WILL RESIDE
#############################################
export TANKverf=${TANKverf:-/com/verf/${envir}}
export TANKverf_rad=${TANKverf_rad:-${TANKverf}/radmon.${PDY}}
export COM_IN=${COM_IN:-/com/${NET}/${envir}}
export COMIN=${COMIN:-$COM_IN/${RADMON_SUFFIX}.${PDY}}

echo "TANKverf: $TANKverf"
echo "TANKverf_rad: $TANKverf_rad"
echo "COM_IN: $COM_IN"
echo "COMIN: $COMIN"

mkdir -p -m 775 $TANKverf_rad

echo "" 
#echo "" 
#env
#echo "" 
echo "" 

########################################
# Set necessary environment variables
########################################
export RAD_AREA=${RAD_AREA:-rgn}
export CYCLE_INTERVAL=${CYCLE_INTERVAL:-1}


#####################################################################
# Note:  The organization to the radstat catch-up files follows
#        this logic:
#####################################################################

case $cyc in
   00) export rgnHH=t00z
       export rgnTM=tm00;;
   01) export rgnHH=t06z
       export rgnTM=tm05;;
   02) export rgnHH=t06z
       export rgnTM=tm04;;
   03) export rgnHH=t06z
       export rgnTM=tm03;;
   04) export rgnHH=t06z
       export rgnTM=tm02;;
   05) export rgnHH=t06z
       export rgnTM=tm01;;
   06) export rgnHH=t06z
       export rgnTM=tm00;;
   07) export rgnHH=t12z
       export rgnTM=tm05;;
   08) export rgnHH=t12z
       export rgnTM=tm04;;
   09) export rgnHH=t12z
       export rgnTM=tm03;;
   10) export rgnHH=t12z
       export rgnTM=tm02;;
   11) export rgnHH=t12z
       export rgnTM=tm01;;
   12) export rgnHH=t12z
       export rgnTM=tm00;;
   13) export rgnHH=t18z
       export rgnTM=tm05;;
   14) export rgnHH=t18z
       export rgnTM=tm04;;
   15) export rgnHH=t18z
       export rgnTM=tm03;;
   16) export rgnHH=t18z
       export rgnTM=tm02;;
   17) export rgnHH=t18z
       export rgnTM=tm01;;
   18) export rgnHH=t18z       # dayfile changes here
       export rgnTM=tm00;;
   19) export rgnHH=t00z
       export rgnTM=tm05;;
   20) export rgnHH=t00z
       export rgnTM=tm04;;
   21) export rgnHH=t00z
       export rgnTM=tm03;;
   22) export rgnHH=t00z
       export rgnTM=tm02;;
   23) export rgnHH=t00z
       export rgnTM=tm01;;
esac

export biascr=${biascr:-$COMIN/${RADMON_SUFFIX}.${rgnHH}.satbiasc.${rgnTM}}
export radstat=${radstat:-$COMIN/${RADMON_SUFFIX}.${rgnHH}.radstat.${rgnTM}}


########################################################
# Execute the script.
echo "EXECUTING ${SCRnam}/exnam_verfrad.sh"
${RADMONSH:-${SCRnam}/exnam_verfrad.sh} ${PDY} ${cyc}
########################################################

################################
# Remove the Working Directory
################################
#KEEPDATA=${KEEPDATA:-NO}
#cd $DATAROOT
#if [ ${KEEPDATA} = NO ] ; then 
#  rm -rf $DATA 
#fi

#date

