name: GCC Linux Build
on: [push, pull_request, workflow_dispatch]


# Use custom shell with -l so .bash_profile is sourced
# without having to do it in manually every step
defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  cache_key: gcc
  CC: gcc-10
  FC: gfortran-10
  CXX: g++-10

# The jobs are split into:
# 1. a dependency build step (setup), and
# 2. a GSI-monitor build step (gsi-monitor)
# The setup is run once and the environment is cached,
# so each subsequent build of GSI-monitor can reuse the cached dependencies to save time (and compute).

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: checkout  # this is to get the ci/spack.yaml file
        uses: actions/checkout@v3
        with:
            path: gsi-monitor

      # Cache spack, compiler and dependencies
      - name: cache-env
        id: cache-env
        uses: actions/cache@v3
        with:
          path: |
            spack
            ~/.spack
          key: spack-${{ runner.os }}-${{ env.cache_key }}-${{ hashFiles('gsi-monitor/ci/spack.yaml') }}

      # Install dependencies using Spack
      - name: install-dependencies-with-spack
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          git clone -c feature.manyFiles=true https://github.com/JCSDA/spack.git
          source spack/share/spack/setup-env.sh
          spack env create gsi-monitor-env gsi-monitor/ci/spack.yaml
          spack env activate gsi-monitor-env
          sudo apt install cmake
          spack external find
          spack add mpich@3.4.2
          spack concretize
          spack install -v --fail-fast --dirty
          spack clean --all

  gsi-monitor:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
            path: gsi-monitor

      - name: cache-env
        id: cache-env
        uses: actions/cache@v3
        with:
          path: |
            spack
            ~/.spack
          key: spack-${{ runner.os }}-${{ env.cache_key }}-${{ hashFiles('gsi-monitor/ci/spack.yaml') }}

      - name: build
        run: |
          source spack/share/spack/setup-env.sh
          spack env activate gsi-monitor-env
          export CC=mpicc
          export FC=mpif90
          cd gsi-monitor
          mkdir -p build && cd build
          cmake -DBUILD_UTIL_ALLMON=ON ..
          make -j2 VERBOSE=1
          make install
