name: Intel Linux Build
on: [push, pull_request, workflow_dispatch]

# Use custom shell with -l so .bash_profile is sourced which loads intel/oneapi/setvars.sh
# without having to do it in manually every step
defaults:
  run:
    shell: bash -leo pipefail {0}

# Set I_MPI_CC/F90 so Intel MPI wrapper uses icc/ifort instead of gcc/gfortran
env:
  cache_key: intel
  CC: icc
  FC: ifort
  CXX: icpc
  I_MPI_CC: icc
  I_MPI_F90: ifort

# The jobs are split into:
# 1. a dependency build step (setup), and
# 2. a GSI-monitor build step (gsi-monitor)
# The setup is run once and the environment is cached,
# so each subsequent build of GSI-monitor can reuse the cached dependencies to save time (and compute).

jobs:
  setup:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout  # this is to get the ci/spack.yaml file
        uses: actions/checkout@v3
        with:
            path: gsi-monitor

      # Cache spack, compiler and dependencies
      - name: cache-env
        id: cache-env
        uses: actions/cache@v3
        with:
          path: |
            spack
            ~/.spack
            /opt/intel
          key: spack-${{ runner.os }}-${{ env.cache_key }}-${{ hashFiles('gsi-monitor/ci/spack.yaml') }}

      - name: install-intel-compilers
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install intel-oneapi-dev-utilities intel-oneapi-mpi-devel intel-oneapi-openmp intel-oneapi-compiler-fortran-2023.2.1 intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2023.2.1
          echo "source /opt/intel/oneapi/setvars.sh" >> ~/.bash_profile

      # Install dependencies using Spack
      - name: install-dependencies-with-spack
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          git clone -c feature.manyFiles=true https://github.com/JCSDA/spack.git
          source spack/share/spack/setup-env.sh
          spack env create gsi-monitor-env gsi-monitor/ci/spack.yaml
          spack env activate gsi-monitor-env
          spack compiler find
          sudo apt install cmake
          spack external find
          spack add intel-oneapi-mpi
          spack concretize
          spack install --dirty -v --fail-fast
          spack clean --all

  gsi-monitor:
    needs: setup
    runs-on: ubuntu-20.04

    steps:
      - name: install-intel
        run: |
          echo "source /opt/intel/oneapi/setvars.sh" >> ~/.bash_profile

      - name: checkout
        uses: actions/checkout@v3
        with:
            path: gsi-monitor

      - name: cache-env
        id: cache-env
        uses: actions/cache@v3
        with:
          path: |
            spack
            ~/.spack
            /opt/intel
          key: spack-${{ runner.os }}-${{ env.cache_key }}-${{ hashFiles('gsi-monitor/ci/spack.yaml') }}

      - name: build
        run: |
          source spack/share/spack/setup-env.sh
          spack env activate gsi-monitor-env
          export CC=mpiicc
          export FC=mpiifort
          cd gsi-monitor
          mkdir -p build && cd build
          cmake -DBUILD_UTIL_ALLMON=ON ..
          make -j2 VERBOSE=1
          make install
